//! Temporary string receivers must use the same native methods and ownership
//! rules as bound strings. No database or external service is involved.

#[path = "support/native_allocation_harness.rs"]
mod native_allocation_harness;
#[allow(dead_code)]
#[path = "support/native_pg_harness.rs"]
mod native_harness;

use ku::{backend::c, checker::Checker, ir, lexer::Lexer, parser::Parser};
use native_allocation_harness::ALLOCATION_HOOK;
use native_harness::{compile_harness, emit_c, run_bounded, TempDir, RUN_LIMITS, RUN_TIMEOUT};
use std::{fs, process::Command};

fn parse(source: &str) -> ku::ast::Program {
    Parser::new(
        Lexer::new(source)
            .tokenize()
            .expect("lex temporary receiver"),
    )
    .parse_program()
    .expect("parse temporary receiver")
}

fn generated(source: &str) -> String {
    let program = parse(source);
    Checker::new()
        .check(&program)
        .expect("check temporary receiver");
    let lowered = ir::lower_program(&program).expect("lower temporary receiver");
    c::generate_c_source(&ir::optimize_program(&lowered)).expect("emit temporary receiver C")
}

const SOURCE: &str = r#"
fn Suffix(): str { return "é" }
fn Load(): str { return "h" + Suffix() }
fn TryLoad(): str! { return ok("h" + Suffix()) }
fn Direct(): int { return Load().byte_len() }
fn Unwrapped(): int! { return ok((TryLoad()?).byte_len()) }
fn FromFunctionValue(): int {
    op: fn(): str = Load
    return op().byte_len()
}
fn main() {}
"#;

#[test]
fn native_temporary_string_methods_lower_without_weakening_indirect_calls() {
    let source = generated(SOURCE);
    assert!(!source.contains("run_source") && !source.contains("const SOURCE"));
    assert!(source.contains("int64_t Direct(void)"));
    assert!(source.contains("KuResult_int Unwrapped(void)"));

    let not_a_function = parse(
        r#"struct Box { byte_len: int }
fn Make(): Box { return Box { byte_len: 7 } }
fn main() { println(Make().byte_len()) }
"#,
    );
    assert!(Checker::new().check(&not_a_function).is_err());
    // The IR verifier is also a boundary for callers that bypass the checker.
    let error = ir::lower_program(&not_a_function).expect_err("integer field is not callable");
    assert!(error
        .to_string()
        .contains("indirect callee is not a function value"));
}

#[test]
fn native_temporary_string_methods_support_mysql_result_payload_without_connecting() {
    let directory = TempDir::new("temporary-mysql-string-method");
    let source = emit_c(
        directory.path(),
        r#"import mysql from "std.mysql"
fn main(): null! {
    client = mysql.client({ host: "127.0.0.1", port: 1, user: "fixture", password: "", database: "fixture" })?
    result = client.query("SELECT ?", ["hé"])?
    println((result.value(0, 0)?).byte_len())
    client.close()
    return ok(null)
}
"#,
    );
    assert!(source.contains("ku_mysql_result_value("));
    // C generation only: neither this source nor any MySQL code is executed.
}

#[test]
fn native_temporary_string_owned_receiver_lives_through_call_and_drops_once() {
    let source = generated(SOURCE);
    let load = "KuString Load(void) {";
    let try_load = "KuResult_str TryLoad(void) {";
    assert!(source.contains(load) && source.contains(try_load));
    let source = source
        .replacen(
            "typedef struct KuString {",
            &format!("{ALLOCATION_HOOK}\n{RECEIVER_ALLOCATION_HOOK}\nstatic size_t load_calls = 0, try_load_calls = 0;\ntypedef struct KuString {{"),
            1,
        )
        .replacen("int main(void) {", "static int ku_generated_main(void) {", 1)
        .replacen(load, &format!("{LIVE_RECEIVER_HOOK}\n{load}\n  load_calls++;"), 1)
        .replacen(try_load, &format!("{try_load}\n  try_load_calls++;"), 1);
    let mut reads = 0;
    let mut harness = String::new();
    for line in source.lines() {
        if let Some((before, after)) = line.split_once("= (int64_t)(") {
            if let Some(receiver) = after.strip_suffix(").len;") {
                reads += 1;
                harness.push_str(&format!("{before}= ku_test_live_byte_len({receiver});\n"));
                continue;
            }
        }
        harness.push_str(line);
        harness.push('\n');
    }
    assert_eq!(reads, 3, "instrument every generated byte_len read");
    harness.push_str(OWNERSHIP_MAIN);
    let directory = TempDir::new("temporary-string-method");
    let source = directory.path().join("temporary-string-method.c");
    fs::write(&source, harness).expect("write temporary receiver allocation harness");
    let Some(executable) = compile_harness(directory.path(), &source, "temporary-string-method")
    else {
        return;
    };
    let output = run_bounded(
        Command::new(executable).current_dir(directory.path()),
        RUN_TIMEOUT,
        RUN_LIMITS,
    )
    .expect("temporary receiver executable must be bounded");
    assert!(
        output.status.success(),
        "temporary string ownership failed:\n{}{}",
        String::from_utf8_lossy(&output.stdout),
        String::from_utf8_lossy(&output.stderr)
    );
    assert_eq!(
        String::from_utf8(output.stdout)
            .expect("ASCII fixture output")
            .replace('\r', ""),
        "temporary-string-method-ok\n"
    );
    assert!(output.stderr.is_empty());
}

// The runtime concat allocates one three-byte string. Static .clone() does not
// allocate, and the top-level function value has a NULL environment. Track the
// actual pointer too, so correct aggregate counts cannot hide a dangling read.
const RECEIVER_ALLOCATION_HOOK: &str = r#"
static void* ku_test_live_pointer = NULL;
static void* ku_test_receiver_malloc(size_t size) {
  void* value = ku_perf_malloc(size);
  if (value) {
    if (ku_test_live_pointer) { fputs("unexpected concurrent fixture allocation\n", stderr); exit(2); }
    ku_test_live_pointer = value;
  }
  return value;
}
static void ku_test_receiver_free(void* value) {
  if (value) {
    if (value != ku_test_live_pointer) { fputs("unexpected fixture allocation free\n", stderr); exit(2); }
    ku_test_live_pointer = NULL;
  }
  ku_perf_free(value);
}
#undef malloc
#undef free
#define malloc ku_test_receiver_malloc
#define free ku_test_receiver_free
"#;

const LIVE_RECEIVER_HOOK: &str = r#"
static int64_t ku_test_live_byte_len(KuString value) {
  if (ku_perf_live_allocations != 1 || ku_perf_live_bytes != 3
      || value.storage != KU_STRING_OWNED || value.capacity != 3
      || value.len != 3 || !value.ptr || value.ptr != ku_test_live_pointer
      || memcmp(value.ptr, "h\xc3\xa9", 3) != 0) {
    fprintf(stderr, "owned receiver mismatch: live=%zu bytes=%zu len=%zu capacity=%zu storage=%u load=%zu try_load=%zu\n",
        ku_perf_live_allocations, ku_perf_live_bytes, value.len, value.capacity,
        (unsigned)value.storage, load_calls, try_load_calls);
    exit(2);
  }
  return (int64_t)value.len;
}
"#;

const OWNERSHIP_MAIN: &str = r#"
#undef malloc
#undef calloc
#undef realloc
#undef free
int main(void) {
  for (size_t round = 0; round < 64; round++) {
    size_t before = ku_perf_calls;
    if (Direct() != 3 || ku_perf_live_allocations != 0) return 3;
    KuResult_int result = Unwrapped();
    if (!result.ok || result.value != 3 || ku_perf_live_allocations != 0) return 4;
    if (FromFunctionValue() != 3 || ku_perf_live_allocations != 0) return 5;
    if (ku_perf_calls != before + 3 || ku_perf_live_bytes != 0
        || ku_test_live_pointer || ku_perf_overflow) return 6;
    if (load_calls != (round + 1) * 2 || try_load_calls != round + 1) return 7;
  }
  puts("temporary-string-method-ok");
  return 0;
}
"#;
